name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.0
  dots_indicator: ^3.0.0
  package_info: ^2.0.2
  shared_preferences: ^2.2.1
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.2
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.2
  intl: ^0.18.1
  cookie_jar: ^4.0.8
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.0+1
  flutter_easyloading: ^3.0.5
  firebase_auth: ^4.10.0
  image_picker: ^1.0.4
  firebase_storage: ^11.2.7
  photo_view: ^0.14.0
  path: ^1.8.3
  pull_to_refresh: ^2.0.0
  # flutter_cache_manager: ^3.3.1
  # crypto: ^3.0.3
  # webview_flutter: ^4.3.0
  # loading_animations: ^2.2.0
  # share: ^2.0.4
  # device_info: ^2.0.3
  # path_provider: ^2.1.1
  permission_handler: ^11.0.0
  # sentry: ^7.10.1
  # uni_links: ^0.5.1
  # flutter_spinkit: ^5.2.0
  # flutter_swiper:
  firebase_messaging: ^14.6.8
  # firebase_in_app_messaging: ^0.7.3+6
  # location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
        - weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
